"""Formal verification bridge: generates SymbiYosys-compatible assertions.

Emits .sby configuration files and SystemVerilog assertion wrappers from
crux structural findings. Users run formal checks with `sby <file>.sby`.

Generated assertions:
- Gray code correctness: $countones(gray ^ $past(gray)) <= 1
- Handshake data stability: data is $stable when control signal is active
- Synchronizer depth: multi-cycle path constraints
"""

from __future__ import annotations

from dataclasses import dataclass
from io import StringIO
from pathlib import Path

from .cdc_check import CDCReport, Crossing, ViolationType
from .synchronizers import Synchronizer


@dataclass
class FormalAssertion:
    """A single formal property to verify."""
    name: str
    clock: str
    property_sv: str        # SystemVerilog assertion body
    description: str


def generate_formal_checks(
    report: CDCReport,
    verilog_files: list[str],
    top_module: str,
) -> tuple[str, str]:
    """Generate .sby config and assertion wrapper from CDC analysis results.

    Returns (sby_content, wrapper_sv_content).
    """
    assertions = _collect_assertions(report)

    if not assertions:
        return "", ""

    wrapper_sv = _generate_wrapper(assertions, top_module)
    sby_config = _generate_sby(verilog_files, top_module)

    return sby_config, wrapper_sv


def _collect_assertions(report: CDCReport) -> list[FormalAssertion]:
    """Extract formal assertions from CDC analysis results."""
    assertions: list[FormalAssertion] = []

    for crossing in report.crossings:
        if not crossing.is_synchronized or not crossing.synchronizer:
            continue

        sync = crossing.synchronizer
        last_stage = sync.stages[-1]
        dst_clock = crossing.dest_domain

        # Gray code assertion: each cycle, at most 1 bit changes
        if crossing.bit_width > 1:
            signal = crossing.signal_name
            assertions.append(FormalAssertion(
                name=f"gray_{signal}",
                clock=dst_clock,
                property_sv=(
                    f"assert($countones("
                    f"{_esc(last_stage.name)}_q ^ $past({_esc(last_stage.name)}_q)"
                    f") <= 1)"
                ),
                description=f"Gray encoding: {signal} changes at most 1 bit per cycle",
            ))

    # Handshake data stability for MULTI_BIT_CDC warnings (handshake-detected)
    for v in report.violations:
        if v.rule == ViolationType.MULTI_BIT_CDC and v.crossing:
            c = v.crossing
            if c.synchronizer:
                # Has sync on control, data should be stable when sampled
                ctrl_name = _esc(c.synchronizer.stages[-1].name)
                data_name = _esc(c.signal_name)
                assertions.append(FormalAssertion(
                    name=f"handshake_stable_{c.signal_name}",
                    clock=c.dest_domain,
                    property_sv=(
                        f"assert(!$rose({ctrl_name}_q) || $stable({data_name}))"
                    ),
                    description=(
                        f"Handshake stability: {c.signal_name} must be stable "
                        f"when {ctrl_name} rises"
                    ),
                ))

    return assertions


def _generate_wrapper(assertions: list[FormalAssertion], top_module: str) -> str:
    """Generate a SystemVerilog wrapper with formal assertions."""
    buf = StringIO()
    buf.write(f"// Auto-generated by crux formal checker\n")
    buf.write(f"// Bind this to {top_module} for formal verification\n\n")
    buf.write(f"module crux_formal_checks;\n\n")

    for a in assertions:
        buf.write(f"  // {a.description}\n")
        buf.write(f"  // Clock: {a.clock}\n")
        buf.write(f"  always @(posedge {a.clock}) begin : {a.name}\n")
        buf.write(f"    if (!$isunknown($past({a.clock})))\n")
        buf.write(f"      {a.property_sv};\n")
        buf.write(f"  end\n\n")

    buf.write(f"endmodule\n")
    return buf.getvalue()


def _generate_sby(verilog_files: list[str], top_module: str) -> str:
    """Generate a SymbiYosys configuration file."""
    buf = StringIO()
    buf.write("[tasks]\n")
    buf.write("bmc\n\n")

    buf.write("[options]\n")
    buf.write("bmc: mode bmc\n")
    buf.write("bmc: depth 20\n")
    buf.write("multiclock on\n\n")

    buf.write("[engines]\n")
    buf.write("smtbmc z3\n\n")

    buf.write("[script]\n")
    for f in verilog_files:
        buf.write(f"read -sv {f}\n")
    buf.write(f"read -sv crux_formal_checks.sv\n")
    buf.write(f"prep -top {top_module}\n\n")

    buf.write("[files]\n")
    for f in verilog_files:
        buf.write(f"{f}\n")
    buf.write("crux_formal_checks.sv\n")

    return buf.getvalue()


def write_formal_output(
    report: CDCReport,
    verilog_files: list[str],
    top_module: str,
    output_dir: str | Path,
) -> list[str]:
    """Write formal verification files to output directory.

    Returns list of generated file paths.
    """
    sby_content, wrapper_content = generate_formal_checks(
        report, verilog_files, top_module
    )

    if not sby_content:
        return []

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    files = []

    sby_path = out / f"{top_module}_cdc.sby"
    sby_path.write_text(sby_content)
    files.append(str(sby_path))

    sv_path = out / "crux_formal_checks.sv"
    sv_path.write_text(wrapper_content)
    files.append(str(sv_path))

    return files


def _esc(name: str) -> str:
    """Escape Yosys internal names for use in SystemVerilog."""
    # Remove $ prefix and replace special chars
    name = name.lstrip("$")
    name = name.replace("\\", "_").replace(".", "_").replace("$", "_")
    return name
